import aiohttp
import logging
from config import XUI_URL, XUI_API_TOKEN

logger = logging.getLogger(__name__)

class XuiAPI:
    def __init__(self):
        self.base_url = XUI_URL.rstrip("/")
        self.session = None

    async def _get_session(self):
        if self.session is None or self.session.closed:
            self.session = aiohttp.ClientSession(headers={"Authorization": f"Bearer {XUI_API_TOKEN}"})
        return self.session

    async def _request(self, method: str, path: str, **kwargs):
        session = await self._get_session()
        async with session.request(method, f"{self.base_url}{path}", **kwargs) as response:
            if response.status == 200:
                return await response.json()
            logger.error(f"3x-ui {method} {path} -> HTTP {response.status}")
            return None

    async def _enabled_inbound_ids(self):
        res = await self._request("GET", "/panel/api/inbounds/options")
        if res and res.get("success"):
            return [i["id"] for i in res.get("obj", []) if i.get("enable")]
        return []

    async def add_client(self, email: str, expiry_time: int = 0, total_gb: int = 0):
        """
        expiry_time: in milliseconds. total_gb: in bytes, 0 means unlimited.
        Attaches the client to every enabled inbound (all nodes/locations).
        uuid/subId are generated by the panel. Returns (uuid, sub_id) or None.
        """
        inbound_ids = await self._enabled_inbound_ids()
        if not inbound_ids:
            logger.error("No enabled inbounds found on 3x-ui panel")
            return None
        payload = {
            "client": {"email": email, "totalGB": total_gb, "expiryTime": expiry_time, "enable": True},
            "inboundIds": inbound_ids,
        }
        res = await self._request("POST", "/panel/api/clients/add", json=payload)
        if not (res and res.get("success")):
            return None
        client = await self.get_client(email)
        return (client["uuid"], client["subId"]) if client else None

    async def get_client(self, email: str):
        res = await self._request("GET", f"/panel/api/clients/get/{email}")
        if res and res.get("success") and res.get("obj"):
            return res["obj"].get("client")
        return None

    async def update_client_expiry(self, email: str, new_expiry_time: int) -> bool:
        # ponytail: update replaces the whole client row, so we fetch-then-merge
        # to avoid wiping totalGB/enable/tgId (confirmed footgun on the live panel).
        client = await self.get_client(email)
        if not client:
            logger.error(f"Client {email} not found for update")
            return False
        payload = {
            "email": email,
            "totalGB": client.get("totalGB", 0),
            "expiryTime": new_expiry_time,
            "enable": client.get("enable", True),
            "tgId": client.get("tgId", 0),
            "limitIp": client.get("limitIp", 0),
        }
        res = await self._request("POST", f"/panel/api/clients/update/{email}", json=payload)
        return bool(res and res.get("success"))

    async def get_client_traffic(self, email: str):
        res = await self._request("GET", f"/panel/api/clients/traffic/{email}")
        return res.get("obj") if res and res.get("success") else None

    async def list_clients(self):
        res = await self._request("GET", "/panel/api/clients/list")
        return res.get("obj", []) if res and res.get("success") else []

    async def close(self):
        if self.session and not self.session.closed:
            await self.session.close()

xui_api = XuiAPI()
